name: Build Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile Hello World
      run: |
        echo '#include <stdio.h>' > hello.c
        echo 'int main() { printf("Hello, World!\\n"); return 0; }' >> hello.c
        gcc hello.c -o hello

    - name: Run Hello World
      run: ./hello

  test:
  build-2:
      runs-on: windows-latest
      needs: build
      steps:
      - uses: actions/checkout@v4
  
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
  
      - name: Compile Hello World
        run: |
          echo '#include <stdio.h>' > hello.c
          echo 'int main() { printf("Hello, World!\\n"); return 0; }' >> hello.c
          gcc hello.c -o hello
  
      - name: Run Hello World
        run: ./hello
